### ISSUE TITLE
Status Page for nightly runs

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark-nightly#104]
The results of the nightly runs are sent as alert notifications to Slack. Similar to the http://check.ocamllabs.io/, it will be good to have a green/red status page indicating if the nightly build for the configuration was successful or not

**Comment by punchagan** [comment]
The dashboard doesn't work on production since the `ocurrent-deployer` doesn't include the `git` metadata when building the docker image. https://github.com/ocurrent/ocurrent-deployer/pull/146 should fix this issue.
