### ISSUE TITLE
Add latency graphs in sequential/parallel web pages

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark-nightly#114]
The instrumented pausetimes which use eventring have been updated to Sandmark at https://github.com/ocaml-bench/sandmark/issues/358. The sequential and parallel web pages should now include the latency, max latency and 99.9th percentile graphs available in the following notebooks:

https://github.com/ocaml-bench/sandmark/blob/429f52f7b0ea9dbe760b3e249a17cd0b7b629e95/notebooks/sequential/sequential.ipynb 

https://github.com/ocaml-bench/sandmark/blob/429f52f7b0ea9dbe760b3e249a17cd0b7b629e95/notebooks/parallel/parallel.ipynb

**Comment by Firobe** [comment]
Can I close this in favor of https://github.com/ocaml-bench/sandmark/issues/420?

**Comment by punchagan** [comment]
I think we also want to show them in the sandmark-nightly UI, which unfortunately doesn't re-use the code from the notebooks.

**Comment by shakthimaan** [comment]
> Can I close this in favor of https://github.com/ocaml-bench/sandmark/issues/420?

We will need both. The Sandmark notebooks are used for prototyping and also by compiler developers if they would like to test the output locally on their machines. If there are any specific improvements, we also make it available in the sandmark-nightly runs.

**Comment by Firobe** [comment]
Understood! I hadn't yet realized the code for both tasks was not shared.

**Comment by punchagan** [comment]
Closed in #130
