### ISSUE TITLE
502s on the Sandmark nightly UI

### ISSUE THREAD

**Issue by punchagan** [ocaml-bench/sandmark-nightly#126]
The latest [deploy](https://deploy.ci.dev/job/2023-05-12/032039-ocluster-build-2e353a) from `main` seems to have worked fine. The Dockerfile works fine when run locally using the `start_docker.sh` script.

**Comment by mtelvers** [comment]
@punchagan The build was completed, but the deployment stalled on updating the docker service.  I have scaled the service to zero and then scaled it back to one instance, and now the deployment has succeeded.  http://sandmark.tarides.com/ now opens

**Comment by punchagan** [comment]
Thanks @mtelvers ! :tada:
