### ISSUE TITLE
Add bestfit variant to sequential benchmarks

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#14]
The best-fit allocator is generally better than the default next-fit allocator [1]. We should include a nightly run that uses the best fit allocator. The best fit allocator can be enabled by setting the `OCAMLRUNPARAM` option `a` to `2`. For example,

```bash
$ OCAMLRUNPARAM="a=2" ./a.out
```

run `a.out` with best-fit policy. The best-fit variant can be named as `4.12+stock+bestfit` and included in the nightly runs. 

[1] https://blog.janestreet.com/memory-allocator-showdown/

**Comment by Deepthi562** [comment]
@kayceesrk I would like to work on this. Could you please brief me on this issue as I am a beginner in this? Thank you.

**Comment by kayceesrk** [comment]
Hi @Deepthi562, this issue is no longer active since OCaml has switched to the best fit allocator by default. 

Pinging @Sudha247 and @shakthimaan, who can point you to other good first issues.

**Comment by Deepthi562** [comment]
@kayceesrk, thank you. @Sudha247 @shakthimaan, please assign me an issue as I want to include this in my final application. Thank you.
