### ISSUE TITLE
Timestamps are not sorted in the parallel_nightly notebook

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#2]
![image](https://user-images.githubusercontent.com/410484/124216787-a2144b80-db14-11eb-95a7-2755352490fd.png)

They should be sorted reverse chronologically.

**Comment by shubhamkumar13** [comment]
This issue is fixed now

![Screenshot from 2021-07-08 04-31-51](https://user-images.githubusercontent.com/13629677/124838967-8510ca00-dfa5-11eb-8777-ab0a677b7286.png)

**Comment by kayceesrk** [comment]
Thanks.
