### ISSUE TITLE
Add 5.00 variants

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#21]
Multicore OCaml now has gone past 4.12.0 and tracks OCaml trunk. `4.12.0+domains+effects` and `4.12+domains` will only have bug fixes, and not include latest developments. We need the following variants in sandmark nightly:

1. OCaml trunk, sequential, runtime (throughput)
2. OCaml 5.00, sequential, runtime
3. OCaml 5.00, parallel, runtime
4. OCaml trunk, sequential, pausetimes (latency)
5. OCaml 5.00, sequential, pausetimes
6. OCaml 5.00, parallel, pausetimes

The variants are ordered by their priorities in the list above; the earlier ones are more important than the latter ones. This is a high-priority issue and would be good to have it before the OCaml 5.00 synchronous review period (the week of Nov 22). It would be useful to split this into independent PRs:

- [x] Sequential runtime (1,2)
- [x] Parallel runtime (3)
- [ ] Pausetimes (4,5,6)

**Comment by kayceesrk** [comment]
5.00 branches are actually called `4.14.0+domains` (for the sake of maintaining compatibility with the OPAM universe and be compatible with the naming that trunk uses; it will be tagged at some later point). 

FYI OCaml trunk is `4.14.0+trunk` and OCaml 5.00 is `4.14.0+domains` in Sandmark. See https://cloud.drone.io/ocaml-bench/sandmark/911.

**Comment by shubhamkumar13** [comment]
Update :  The current status is still the same, no progress has been made on pausetimes

**Comment by punchagan** [comment]
Closing an old/stale issue
