### ISSUE TITLE
Sandmark nightly issues (19/12/21)

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#23]
There are several issues with sandmark.ocamllabs.io service currently. I'm listing them down here:

## sequential + navajo

The 19/12 nightly run results are available for `5.00+trunk` but not for `4.14.0+domains`. See:

![image](https://user-images.githubusercontent.com/410484/146665645-de2a5d62-c6f8-4a0b-b6e4-3d611a64fb33.png)

The last date on which `4.14.0+domains` was available was 11/12. Recent results are missing. See:

![image](https://user-images.githubusercontent.com/410484/146665653-dc2c9461-96d7-4aad-a2fa-8ceff9b7aa55.png)

## sequential + turing

The 18/12 nightly run results are available for `5.00+trunk` but not for `4.14.0+domains`. See:

![image](https://user-images.githubusercontent.com/410484/146665738-4b8f9a70-a607-4b6c-8da8-abc1b8fe0d55.png)

The last date on with `4.14.0+domains` was available was 13/12. Recent results are missing. See:

![image](https://user-images.githubusercontent.com/410484/146665759-f49eb4d8-c389-45eb-9efd-6673b6fcbbc0.png)

## parallel + navajo

The last date on which the results are available is 13/12. And that too produces errors. See: 

![image](https://user-images.githubusercontent.com/410484/146665819-aedc16f9-e05f-41c1-9787-57e9419e5eb9.png)

The last date on which hte results are available and working is 25/11. See: 

![image](https://user-images.githubusercontent.com/410484/146665850-611fa5fa-45d3-40c6-90b2-bdda23e29d0d.png)

## parallel + turing

The last date on which the results are available is 13/12. Recent results are missing. See:

![image](https://user-images.githubusercontent.com/410484/146665791-6716c048-7432-4d60-bb97-6a866211f3db.png)

## pausetimes results

They are no longer being run nightly as the `5.00+trunk` and `4.14.0+domains` branches don't have the necessary dependencies building IINM (please confirm this, and provide details of the failing dependencies). The page should include a clear message that says that the nightlies are not running:

![image](https://user-images.githubusercontent.com/410484/146665897-e694359d-46cb-4b6b-a6bb-4381d248d137.png)

**Comment by shubhamkumar13** [comment]
https://github.com/ocaml-bench/sandmark-nightly/pull/31 adds archive message for instrumented pausetimes

**Comment by kayceesrk** [comment]
This issue has multiple tasks. Can you use a check list to keep track of completion.

- [ ] task 1
- [ ] task 2
- [x] task 3

**Comment by shubhamkumar13** [comment]
Update : 

- [ ] sequential + navajo : this was before multicore was merged into trunk so this problem might not apply now

- [ ] sequential + turing : this was before multicore was merged into trunk so this problem might not apply now

- [ ] parallel + navajo : this issue also mentions multicore before it was merged but the latest results were also broken which isn't the case right now 
<img width="919" alt="Screenshot 2022-02-02 at 7 59 10 AM" src="https://user-images.githubusercontent.com/13629677/152084208-df3cce14-5509-4339-b6fc-97816ce5f8fa.png">

- [ ] parallel + turing : the recent results are up 
<img width="919" alt="Screenshot 2022-02-02 at 8 01 49 AM" src="https://user-images.githubusercontent.com/13629677/152084549-f3e8a618-152c-4ee4-941a-2114b18cb205.png">

- [ ] pausetimes results - an archived message has been added
<img width="919" alt="Screenshot 2022-02-02 at 7 54 33 AM" src="https://user-images.githubusercontent.com/13629677/152083841-72e9758f-101d-454d-8924-16aa25152278.png">
<img width="919" alt="Screenshot 2022-02-02 at 7 54 33 AM" src="https://user-images.githubusercontent.com/13629677/152083870-12a761d1-0179-45ad-84be-75fbc91a61a7.png">
 
 most of the issues mentioned here are resolved or stale I think it's ok to close this
