### ISSUE TITLE
Change streamlit page title and favicon

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#25]
Currently sandmark nightly tabs are shown as 

![image](https://user-images.githubusercontent.com/410484/148341125-32bd070f-93ef-42c8-aae3-eea285581fdd.png)

It would be useful to customise it to set page title as "Sandmark Nightly" and page icon as "🐫". See

https://docs.streamlit.io/library/api-reference/utilities/st.set_page_config

**Comment by shubhamkumar13** [comment]
https://github.com/ocaml-bench/sandmark-nightly/pull/35 fixes this
