### ISSUE TITLE
Include baseline variant information in the normalised graphs

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#27]
Here is a graph that I generated recently

![image](https://user-images.githubusercontent.com/410484/148656854-9533326e-afab-4529-a7f2-7b62ca5bd967.png)

Observe that the baseline variant information is not present in the normalised graph. The choices that generated the graph are:

![image](https://user-images.githubusercontent.com/410484/148656880-e437d7d7-8c00-4aa3-9a53-2425bf3b38d2.png)

I've had to separately include information about the baseline variant used for normalisation (`4.12.0` stock OCaml version). It would be useful to include the baseline variant information in the graph title (See https://www.statology.org/seaborn-title/). Currently, the title is empty.

**Comment by shubhamkumar13** [comment]
https://github.com/ocaml-bench/sandmark-nightly/commit/b83cea84a74b9b4d28198a02ad4e6e704c62257a adds the baseline info in the normalized graphs so the graph now contains the information for the baseline
