### ISSUE TITLE
Make number of default variants to be 1 in parallel benchmarks

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#28]
https://github.com/ocaml-bench/sandmark-nightly/blob/ed16f2247ffa959001d4fc70a1ed45630d441927/app/apps/parallel_benchmarks.py#L29

**Comment by shubhamkumar13** [comment]
Thanks for resolving this issue -> https://github.com/ocaml-bench/sandmark-nightly/commit/e60661327178d6ad25c9c13cdc008b1ffcfb808c
I think this issue can be closed
