### ISSUE TITLE
Support custom variants from private Github repo

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#32]
With ocaml speed, we had the ability for external users to request custom compiler variants to be added to the nightly run. Sandmark nightly doesn't support it now. 

This feature has been discussed couple of times with the Sandmark developers, and is currently in the roadmap. Adding this issue here, so that we track such roadmap items publicly.

In OCaml speed, the feature included a private Github repo (https://github.com/ocamllabs/ocaml-bench-config) with yaml files, that had the information necessary for custom variants. CC @shakthimaan @shubhamkumar13.

**Comment by punchagan** [comment]
We support that now with the [Sandmark nightly config](https://github.com/ocaml-bench/sandmark-nightly-config/) repo.
