### ISSUE TITLE
Parallel benchmarks should be run on ocaml/ocaml#trunk

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#34]
The parallel benchmarks are only being run on the 5.00+domains variant which points to ocaml-multicore/ocaml-multicore#5.00. This branch is no longer in development since multicore is merged with upstream OCaml. The parallel benchmarks should now be run on ocaml/ocaml#trunk. No need to run the benchmarks on ocaml-multicore/ocaml-multicore#5.00 hereafter. 

CC @shubhamkumar13 @shakthimaan.

**Comment by shubhamkumar13** [comment]
Currently sandmark-nightly is using ocaml trunk to run the parallel benchmarks
<img width="919" alt="Screenshot 2022-02-02 at 8 24 40 AM" src="https://user-images.githubusercontent.com/13629677/152086271-2e0441a3-710c-4c94-9068-085907339352.png">
<img width="919" alt="Screenshot 2022-02-02 at 8 24 53 AM" src="https://user-images.githubusercontent.com/13629677/152086275-c7e44006-72b8-4fc0-90d1-3f53db9fa4d8.png">

and the drone ci on the main branch also uses trunk for parallel runs -> https://github.com/ocaml-bench/sandmark/blob/f43f30a059b0b4c387fe4b49341660320aa47322/.drone.yml#L82-L108
