### ISSUE TITLE
Add a custom run to Sandmark nightly

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#36]
@avsm has a request to add a custom run to sandmark nightly. Let's add this to `turing` and `navajo` for sequential and parallel runs. 

> Compiler variant https://github.com/avsm/ocaml/tree/openbsd-mmap-stack
> 
> It would be helpful to have a configure option added: --enable-mmap-map-stack and --disable-mmap-map-stack

**Comment by avsm** [comment]
Linking to https://github.com/ocaml/ocaml/pull/10875 as the upstream issue.

**Comment by shakthimaan** [comment]
The results have been shared based on the custom run at https://github.com/ocaml/ocaml/pull/10875#issuecomment-1029838604. Hence, closing this issue.
