### ISSUE TITLE
Sequential results comparison is broken

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#37]
![image](https://user-images.githubusercontent.com/410484/151483952-8b7b4733-4410-44e9-8e6b-9e1460a408ee.png)

**Comment by shubhamkumar13** [comment]
https://github.com/ocaml-bench/sandmark-nightly/commit/2e59f8a62a04463116b1f1ea0a55bd4f09a21138 fixes the issue related this crash, this issue was a result of using the updated `.bench` results which included an extra line which was causing an issue.
