### ISSUE TITLE
Baseline for normalised graphs are missing entries

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#38]
Consider this selection with 5 variants. 

![image](https://user-images.githubusercontent.com/410484/151647291-ea290e6c-a5e3-4b5d-8767-cdb3c13162e9.png)

Each variant has a different commit. So we expect each one of these to be present in the normalised graph selection. But observe that only two of the variants show up. 

We expect all of the variants to be available in the dropdown list of the baseline.

**Comment by shubhamkumar13** [comment]
so the 2 variants that show up are for `turing` if we switch to `navajo` we get the other 3 variants.
<img width="919" alt="Screenshot 2022-02-17 at 2 21 35 AM" src="https://user-images.githubusercontent.com/13629677/154354948-f5a9f4ac-ac14-4cea-aa6b-3874013c7339.png">

**Comment by kayceesrk** [comment]
Ah. Ok. I see the problem. Thanks :-)
