### ISSUE TITLE
Parallel results can't be seen on sandmark.ocamllabs.io

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#39]
![image](https://user-images.githubusercontent.com/410484/151649457-d2f37e86-4c9a-4474-b518-be2a88f9bb23.png)

**Comment by shubhamkumar13** [comment]
https://github.com/ocaml-bench/sandmark-nightly/commit/182781b6c94d6755c16e0f569b92417176f91b82 fixes this
![Screenshot from 2022-02-01 09-57-35](https://user-images.githubusercontent.com/13629677/151912845-67007b2b-d612-4e27-b171-6dceb1d0f43e.png)
