### ISSUE TITLE
Parallel notebook pausetimes graphing for navajo results throws an error

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#4]
The configuration chosen are:

![image](https://user-images.githubusercontent.com/410484/124217615-40ed7780-db16-11eb-9025-7b20f043946d.png)

The error is:

![image](https://user-images.githubusercontent.com/410484/124217572-3337f200-db16-11eb-9e13-7def77a5cba7.png)

**Comment by punchagan** [comment]
Closing old/stale issue
