### ISSUE TITLE
The information in the landing page is out of date

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#40]
The variants certainly are, but there may be others that are out of date as well: https://sandmark.ocamllabs.io/

**Comment by shubhamkumar13** [comment]
https://github.com/ocaml-bench/sandmark-nightly/commit/95df25f8503745ce53903326d222904ffa2c734a : updated the landing page to display `stable` and `trunk` variant and remove `domains` variant info which is not longer in use
