### ISSUE TITLE
Show Sandmark branch and version in the UI

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark-nightly#41]
At present, it is not clear from the UI as to which commit and branch in Sandmark is used to build the benchmarks. This information will be useful to have in the UI.

**Comment by shubhamkumar13** [comment]
fix commit -> https://github.com/ocaml-bench/sandmark-nightly/commit/e6c1f212a2fcfc239ee904e29d2204906ae01253 to add sandmark info on the landing page
