### ISSUE TITLE
Status of disabled benchmarks

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#5]
We have this filter in the notebook:

![image](https://user-images.githubusercontent.com/410484/124217709-6f6b5280-db16-11eb-9522-b0107e2be4d4.png)

This was put in back in 2019 March while working on the ICFP paper. Is it the case that these benchmarks still don't work with Multicore OCaml?

**Comment by shubhamkumar13** [comment]
Notebooks are ported from the sandmark-nighty as mentioned in https://github.com/ocaml-bench/sandmark-nightly/issues/45#issue-1140882165 so this issue should be moved to sandmark

**Comment by shubhamkumar13** [comment]
I've created a PR instead of creating a duplicate issue in sandmark
