### ISSUE TITLE
Select date and show multiple variant entries for the same

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark-nightly#60]
The present UI shows a drop-down menu of timestamp as shown in the illustration:

<img width="302" alt="variant-dropdown" src="https://user-images.githubusercontent.com/312622/177251672-0edf9c15-f000-4a4c-9c43-ee3861f810d7.png">

But, for a given timestamp, we do not know which variant was run. We do not need separate timestamp and variant boxes.

The required UI functionality is as follows:
1. Select hostname
2. Select a date.
3. List all the multiple variants separately to select from.

**Comment by kayceesrk** [comment]
> List all the multiple variants separately to select from.

If you have more than one run of the same variant on a given day (which may happen if you manually test it), then there will be duplicate variants listed for that day. You'll need to ensure that the UI can handle that.
