### ISSUE TITLE
Are the results of Turing affected by the JCC erratum microcode update?

### ISSUE THREAD

**Issue by gadmm** [ocaml-bench/sandmark-nightly#85]
Intel processors, among which Xeons of the Skylake family, had a bug which was fixed via a microcode update which could result in decreased performance for jumps placed on 32-bit boundaries. I noticed (and learnt this from Stephen Dolan who noticed the same) that this can greatly impact the result of microbencharks and hot loops, by increasing code layout effects. Intel has issued a recommendation to mitigate the performance impact of this erratum and microcode update, by recompiling software with a special set of compiler options. See https://www.intel.com/content/www/us/en/support/articles/000055650/processors.html

Isn't Turing among the affected CPUs? If so, could the workaround be applied?

This means running OCaml's configure script as follows before compiling OCaml:

```sh
# gcc
./configure CC='gcc -Wa,-mbranches-within-32B' AS='as -mbranches-within-32B'
# clang
./configure CC='clang -mbranches-within-32B-boundaries' AS='as -mbranches-within-32B'
```

**Comment by shakthimaan** [comment]
The present benchmarking machines have the configuration and settings as described in the following document:
https://github.com/ocaml-bench/ocaml_bench_scripts#notes-on-hardware-and-os-settings-for-linux-benchmarking

Turing has an Intel Xeon CPU from the Skylake family. 
```
$ lscpu
...
CPU family:        6
Model:                85
Model name:      Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
Stepping:           4
...
```

If compiler options need to be passed when building the OCaml compiler in Sandmark, the `configure` section in the `ocaml-versions/*.json` file can include these specific options. 

Please refer to the `Configuration of the compiler build` section in the README file for more documentation:
https://github.com/ocaml-bench/sandmark

**Comment by gadmm** [comment]
Thanks for the details. This all looks fine except for disabling ASLR (instead of sampling over several runs).

Digging further, the processor is indeed affected by the JCC erratum, and Intel recommends the application of mitigations (https://www.intel.com/content/dam/support/us/en/documents/processors/mitigations-jump-conditional-code-erratum.pdf):

| Family_Model | Stepping | Processor Families/Processor Number series |
|---|---|---|
| 06_55H | 4 | Intel® Xeon® Scalable Processors based on microarchitecture code name Skylake Server |

Applying the configure options above on all benchmark configurations for Turing is therefore recommended.

It is possible that you have been observing this bug. Indeed the notes https://github.com/ocaml-bench/notes/blob/master/apr19.md mention the perf counters related to DSB as a sign for detrimental alignment effects, and the JCC erratum description mentions them as well.

**Comment by gadmm** [comment]
(cc @kayceesrk)

**Comment by kayceesrk** [comment]
It may be worth incorporating this fix for the default runs @shakthimaan. Perhaps also add a note about this to README.md?
