### ISSUE TITLE
Static html pages for the recent results

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#9]
It would be useful to generate static html pages for the two most recent benchmark runs. The idea is that we can host these pages for everyone to see given that the jupyter notebooks are access controlled. We need 4 html pages generated from the notebooks:

1. Turing, Sequential
2. Turing, Parallel
3. Navajo, Sequential
4. Navajo, Parallel

These html pages can then be hosted on the ec2 machine serving the notebook. CC @shakthimaan please can you help @shubhamkumar13 with assigning default arguments for the interactive bits in the notebook.

**Comment by shubhamkumar13** [comment]
The sandmark-nightly UI is currently hosted in [sandmark.ocamllabs.io](https://sandmark.ocamllabs.io) which resolves this issue
