### ISSUE TITLE
Additional checks on alert notification

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark-nightly#95]
The following additional checks need to be added to be marked as failure for alert notification:
1. If only the line header is present in the output.
2. Check for any errors in the log output. For example, `mtime.1.2.0` is failing to build with `5.1.0+trunk`, even though the sequential benchmark output file exists.

**Comment by punchagan** [comment]
So, in these cases we also don't want to copy the commit to `main`, right? Or do we want to only alert about these failures but continue to copy the commits? :thinking:

**Comment by shakthimaan** [comment]
Ideally, we want to have a clean build for every benchmark run. As the development progresses at a fast pace, packages do break. It is okay to copy completed results, but, we need to have detailed alerts, so that they can be fixed ASAP.

**Comment by punchagan** [comment]
This can be closed after #100 and #103
